/**
 * Publishes the design canvases as a client section on snackbyte-site.
 *
 * Converts each .dc.html canvas under design/ into a complete standalone HTML
 * page and writes the section — pages plus section.json — into the site
 * checkout, per that repo's docs/SECTIONS.md contract. The canvas editor
 * runtime (support.js, the <x-dc> wrapper) is dropped: the canvases are
 * flow-layout HTML with inline styles and render without it.
 *
 * The site path is a required argument so a wrong path fails where you can see
 * it instead of writing files somewhere unnoticed:
 *
 *   node scripts/publish-to-site.mjs /path/to/snackbyte-site
 *
 * Afterwards, run the site's gate from the site repo:
 *   npm run check:all && npm run build
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DESIGN_DIR = fileURLToPath(new URL('../design/', import.meta.url));

const SECTION_SLUG = 'grimoire';

const PAGES = [
  {
    src: 'Grimoire.dc.html',
    path: 'design',
    pageTitle: 'Grimoire Design Canvas',
    card: {
      title: 'Design Canvas',
      blurb:
        'Four design turns, newest first — the spellbook, the composer, records and refusals, and the states board.',
      status: 'Turn 4',
    },
  },
  {
    src: 'GrimoireIcon.dc.html',
    path: 'icon',
    pageTitle: 'Grimoire App Icon',
    card: {
      title: 'App Icon',
      blurb: 'The Discord app icon at 512×512, with its construction alongside.',
      status: 'Candidate',
    },
  },
];

const SECTION = {
  title: 'Grimoire',
  blurb:
    'A platform for performative speech in chat communities: spells — stored sentences that do things when spoken. Design work, before the screens are built.',
  pages: PAGES.map((p) => ({ path: p.path, ...p.card })),
};

/**
 * Converts a design canvas (.dc.html) to a complete standalone page: the
 * <helmet> content becomes the head, everything between </helmet> and </x-dc>
 * becomes the body, and the canvas-editor runtime is left behind.
 */
export function convertCanvas(html, pageTitle) {
  const helmetOpen = html.indexOf('<helmet>');
  const helmetClose = html.indexOf('</helmet>');
  const canvasClose = html.indexOf('</x-dc>');
  if (helmetOpen === -1 || helmetClose === -1 || canvasClose === -1) {
    throw new Error('not a canvas file: missing <helmet> or <x-dc> markers');
  }

  const head = html
    .slice(helmetOpen + '<helmet>'.length, helmetClose)
    .replace(/^\s*<meta name="design_doc_mode"[^>]*>\s*$\n?/m, '');
  const body = html.slice(helmetClose + '</helmet>'.length, canvasClose);

  const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>${pageTitle}</title>
${head.trim()}
</head>
<body>
${body.trim()}
</body>
</html>
`;

  for (const leak of ['support.js', '<x-dc', 'design_doc_mode']) {
    if (page.includes(leak)) {
      throw new Error(`conversion leaked canvas runtime into the page: ${leak}`);
    }
  }
  return page;
}

function main() {
  const sitePath = process.argv[2];
  if (!sitePath) {
    console.error('usage: node scripts/publish-to-site.mjs /path/to/snackbyte-site');
    process.exit(1);
  }
  if (!existsSync(join(sitePath, 'docs', 'SECTIONS.md'))) {
    console.error(`${sitePath} does not look like a snackbyte-site checkout (no docs/SECTIONS.md)`);
    process.exit(1);
  }
  const workDir = join(sitePath, 'src', 'web', 'public', 'work');
  if (!existsSync(workDir)) {
    console.error(`${workDir} does not exist — is this checkout current?`);
    process.exit(1);
  }

  const sectionDir = join(workDir, SECTION_SLUG);
  for (const page of PAGES) {
    const html = readFileSync(join(DESIGN_DIR, page.src), 'utf8');
    const out = convertCanvas(html, page.pageTitle);
    mkdirSync(join(sectionDir, page.path), { recursive: true });
    writeFileSync(join(sectionDir, page.path, 'index.html'), out);
    console.log(`wrote ${SECTION_SLUG}/${page.path}/index.html (${out.length} bytes)`);
  }
  // The section root index.html is generated by the site's build — never written here.
  writeFileSync(join(sectionDir, 'section.json'), JSON.stringify(SECTION, null, 2) + '\n');
  console.log(`wrote ${SECTION_SLUG}/section.json`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
