#!/usr/bin/env bash
#
# Project a deployed tier's config out of Secret Manager into a local dotenv file.
#
#   scripts/pull-env.sh <staging|prod>      # writes .env.<env>
#
# The written file is a DISPOSABLE PROJECTION, not a source of truth. Secret Manager
# (grimoire-<env>-*) is canonical; this file is a convenience copy you can delete and
# regenerate whenever. That is the whole point of generating rather than hand-maintaining it:
# a hand-copied secret drifts silently from the real one and nobody notices until it is wrong,
# which is the exact failure the deployed side already avoids by reading Secret Manager live.
#
# The environment MUST be named. An unknown name is a hard stop — never a default, because the
# default would write the wrong tier's production credentials into a file named for another.
#
# .env.local is NOT generated here. It points at your local Postgres and a dev bot, holds no
# cloud secret, and is maintained by hand from .env.local.example.
set -euo pipefail

env_name="${1:-}"
case "$env_name" in
  staging | prod) ;;
  *)
    echo "usage: scripts/pull-env.sh <staging|prod>   (writes .env.<env> from Secret Manager)" >&2
    echo "       .env.local is hand-maintained from .env.local.example, not generated." >&2
    exit 2
    ;;
esac

fetch() {
  gcloud secrets versions access latest --secret="$1" 2>/dev/null || {
    echo "could not read secret '$1' (is gcloud authenticated, and does the secret exist?)" >&2
    exit 1
  }
}

out=".env.${env_name}"
umask 077 # the file is created 600 — it holds a real secret
{
  echo "# GENERATED by scripts/pull-env.sh ${env_name} — do not edit by hand."
  echo "# Source of truth is Secret Manager (grimoire-${env_name}-*). Delete and regenerate to refresh."
  echo "DATABASE_URL=$(fetch "grimoire-${env_name}-database-url")"
  echo "DISCORD_BOT_TOKEN=$(fetch "grimoire-${env_name}-discord-bot-token")"
  echo "LOG_LEVEL=info"
  echo "PORT=8080"
} >"$out"
chmod 600 "$out"

echo "wrote ${out} (mode 600) from grimoire-${env_name}-* — a disposable projection; Secret Manager is canonical."
echo "run with: node --env-file=${out} scripts/<script>.mjs"
